name: kokylive
description: A new project created by matrixclouds.com

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.10
  json_serializable: ^3.4.1
  provider: ^4.3.2+1
  dio: ^3.0.10
  json_annotation: ^3.0.1
  cached_network_image: ^2.3.1
  awesome_dialog: ^1.2.0
  carousel_slider: ^2.2.1
  auto_size_text: ^2.1.0
  shimmer: ^1.1.1
  social_media_buttons: ^0.1.2
  url_launcher: ^5.5.1
  flutter_widget_from_html_core: ^0.4.3
  google_fonts: ^1.1.0
  # esys_flutter_share: 
  pull_to_refresh: ^1.6.1
  swipeable_page_route: ^0.1.4
  steps_indicator: ^1.0.1
  introduction_screen: ^1.0.9
  flutter_spinkit: ^4.1.2+1
  avatar_glow: ^1.2.0
  animated_text_kit: ^2.2.0
  circular_reveal_animation: ^1.1.5
  flushbar: ^1.10.4
  permission_handler: ^5.0.1+1
  easy_localization: ^2.3.3
  webview_flutter: ^0.3.22+1
  http_auth: ^0.3.0
  http: ^0.12.2
  photo_view: ^0.10.2
  flutter_range_slider: ^1.4.0
  # todo android proguard & ios configuration
  # agora_rtc_engine: ^1.0.15
  # agora_rtc_engine: ^4.2.0
  # agora_rtc_engine: ^3.3.0-rc.0

  # todo ios configuration
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  image_picker: ^0.6.7+4
  flutter_plugin_android_lifecycle: ^1.0.11
  flutter_widget_from_html : ^0.4.3
#  connectivity: ^0.4.9
#  image_picker: ^0.6.7+4
#  path_provider: ^1.6.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_launcher_icons: ^0.7.5
#
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/img/logo.png"
##flutter pub run flutter_launcher_icons:main



flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/img/